on:
  push:
    branches: [main, master]
  schedule:
    - cron: '0 12 * * *'

jobs:
  update-dashboard:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    
    steps:
      - name: Set up R
        uses: r-lib/actions/setup-r@v2
        with:
          r-version: '4.4.1'

      - name: Install packages
        uses: r-lib/actions/setup-r-dependencies@v2
        with:
          packages: |
            any::igraph
            any::dplyr
            any::lubridate
            any::tidyr

      - name: Check out repository
        uses: actions/checkout@v4
      
      - name: Set up Quarto
        uses: quarto-dev/quarto-actions/setup@v2

      - name: Render and Publish
        uses: quarto-dev/quarto-actions/publish@v2
        with:
          target: gh-pages
          path: |
            ./index.qmd
            ./explain.qmd

        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
